name: Update Course Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,8,16 * * *'
jobs:
  UpdateData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: checkout gh-page
        run: |
          git checkout gh-page

      - name: pull data
        run: |
          python3 updateData.py 113 2 1
      
      - name: commit and push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git status
          git add 1132-data.json
          git commit -m "Update data"
          git push
